run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - ineffassign
    - errcheck
    - unused
    - gosimple

issues:
  exclude-dirs:
    - darts-fe
    - bin
  exclude-files:
    - '^.*_test\.go$'
