version: '3'

vars:
  APP_NAME: darts-counter
  BIN_DIR: bin
  BUILD_OUT: '{{.BIN_DIR}}/{{.APP_NAME}}'

# Tasks for building, testing, and linting the Go backend
# Requires:
# - Go toolchain
# - golangci-lint for `task lint` (configured via .golangci.yml)

tasks:
  build:
    desc: Build the Go server into bin/darts-counter
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BUILD_OUT}} ./cmd/server

  test:
    desc: Run all Go tests with coverage
    cmds:
      - go test ./... -cover

  lint:
    desc: Run golangci-lint with repository configuration
    cmds:
      - golangci-lint run
